### ISSUE TITLE
Some assistance with usage please

### ISSUE THREAD

**Issue by 0ut4t1m3** [kdschlosser/mp_lcd_bus#1]
Hi there,

Could I bug you for a little help with getting this module to work please? I have a LCD with a parallel interface and I've had no end of trouble trying to get it to work in Micropython. Your module sounds like it might be what I'm needing but I'm struggling a bit without documentation.

By following the official docs I have been able to successfully compile Micropython with your module but I'm having a hard time trying to work out how to get it going. This is what I have managed to scrape together looking at your code but I'm getting a kernel panic at the init so I think I need some help lol:

```
import lcd_bus

tft = lcd_bus.RGBBus(hsync=46,vsync=3,de=5,disp=-1,pclk=7,
               data0=14,data1=38,data2=18,data3=17,data4=10,data5=39,data6=0,data7=45,
               data8=48,data9=47,data10=21,data11=1,data12=2,data13=42,data14=41,data15=40)

tft.init(800,480,16,768000,0)  #<< crashes here
```

I'm sure it's something I'm missing but just in case this is the crash dump:
```
MPY: soft reboot
Guru Meditation Error: Core  1 panic'ed (InstrFetchProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x00000000  PS      : 0x00060f30  A0      : 0x82002747  A1      : 0x3fceda90  
A2      : 0x00000000  A3      : 0x00000320  A4      : 0x000001e0  A5      : 0x00000010  
A6      : 0x000bb800  A7      : 0x3fceda90  A8      : 0x82002bac  A9      : 0x3fceda80  
A10     : 0x3c1818ec  A11     : 0x00000320  A12     : 0x000001e0  A13     : 0x00000010  
A14     : 0x000bb800  A15     : 0x00000850  SAR     : 0x00000002  EXCCAUSE: 0x00000014  
EXCVADDR: 0x00000000  LBEG    : 0x400570e8  LEND    : 0x400570f3  LCOUNT  : 0x00000000  


Backtrace: 0xfffffffd:0x3fceda90 0x42002744:0x3fcedad0 0x4201926d:0x3fcedb20 0x4201ff49:0x3fcedb50 0x4202000d:0x3fcedb70 0x4037a6ea:0x3fcedb90 0x42019213:0x3fcedc30 0x4201ff49:0x3fcedc60 0x4201ff5e:0x3fcedc80 0x4202c4e6:0x3fcedca0 0x4202c626:0x3fcedd30 0x42033c66:0x3fcedd80
```

**Comment by kdschlosser** [comment]
I have not updated this in a while. If you want something that is more complete, is actively being worked on and is mostly functional then look here.

https://github.com/kdschlosser/lvgl_micropython

If you are not interested in using LVGL you can compile it using only the bus drivers and if that is what you want to do lemme know and I can tell you hot to do it.

**Comment by 0ut4t1m3** [comment]
Oh okay thankyou. If you wouldn't mind giving me a few steps on how to use the driver on its own that would be awesome, I was trying to avoid having to go with a full LVGL setup.

Ideally I'm looking to have a buffer or two I can manage with framebuf on the uP side.

**Comment by kdschlosser** [comment]
What are you using for an MCU??

The reason I ask is I have not yet fully implemented the drivers for all the different MCUs. The ESP32 has the most done so far.

**Comment by kdschlosser** [comment]
to compile without compiling LVGL with it.

ESP32:
```
make -C lib/micropython/mpy-cross
make submodules -C lib/micropython/ports/esp32
make -C lib/micropython/ports/esp32 SECOND_BUILD=0 LV_PORT=esp32 BOARD={board} BOARD_VARIANT={board_variant} USER_C_MODULES=../../../../../ext_mod/lcd_bus/micropython.cmake
```

STM32
for this one you have to delete `ext_mod/lvgl/micropython.cmake` before compiling
```
make -C lib/micropython/mpy-cross
make submodules -C lib/micropython/ports/stm32
make -C lib/micropython/ports/stm32 LV_PORT= stm32 BOARD={board} LV_CFLAGS="-DLV_USE_TINY_TTF=0" USER_C_MODULES={absolute_path_to}/ext_mod
```

RP2:
```
make -C lib/micropython/mpy-cross
make submodules -C lib/micropython/ports/rp2
make -C lib/micropython/ports/rp2 SECOND_BUILD=0 LV_PORT=rp2 BOARD={board} USER_C_MODULES=../../../../../ext_mod/lcd_bus/micropython.cmake
```

replace `{board}` with the board you are compiling for and `{board_variant}` gets set to the variant. `{absolute_path_to}` need to be the absolute path to the ext_mod folder.

**Comment by 0ut4t1m3** [comment]
> What are you using for an MCU??
> 
> The reason I ask is I have not yet fully implemented the drivers for all the different MCUs. The ESP32 has the most done so far.

I'm working with an ESP32-S3, [this](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-4.3) is the board if you're curious.

Thank you for the instructions I'll make a build today and let you know how I go.

**Comment by kdschlosser** [comment]
I have not yet looked at the code for the framebuffer that is built into MicroPython. I have to take a look to see if it can be passed to the bus instance so it will flush the data to the display.

**Comment by kdschlosser** [comment]
That display is not going to be the most ideal to use if you are using the build in framebuffer in MicroPython. This is because the display you are wanting to use is an RGB display. It has no GRAM on it. So you are going to have to manage 2 frame buffers and when to write to which one and the frame buffer data needs to be copied from one buffer to the other to keep them synchronized. The reason why is you cannot write to a buffer while it is being sent and if you have a blocking send which you can do the issue will be how long it takes you to write to the buffer and then send it again. It's not going to be fast enough and you will end up with anomalies that appear. You are going to want to use DMA memory and 2 buffers to work around that problem.  This is where it gets complicated to keep things synchronized properly and the big issue is MicroPython only uses a single core of the ESP32. The challenge there is if you perform any other tasks in MicroPython it could end up causing tearing of the frames. Everything gets really time sensitive.

I have that exact same display sitting right in front of me. It does work with the driver which is a good thing. You just have to write really efficient code to use it properly.

**Comment by kdschlosser** [comment]
You are going to need to have the bus driver create the frame buffers. This is done by calling `bus.allocate_framebuffer(size, flags)` the returned object is going to be a memory view object and that object is going to have a size of 1 until you initialize the bus. we can get into all of that once you get it compiled.

**Comment by 0ut4t1m3** [comment]
I was wanting to explore displays using more than just SPI. In hindsight I was a bit naive with this one and missed the lack of any internal framebuffer, I'm still pretty green with C on this platform so I wasn't planning to need to manage such high data rates and timing with uP. I might need to do some playing around with it in the ESP-IDF for a while so I can get a bit more familiar with C so I can help contribute.

I know this is heading away from your own project goals but if you're curious I'm thinking of a background task for the bus driver, maybe running on the second core. It would manage the hardware and pumping data from a buffer to the screen at the right rate. On buffers I would have two but let the user manage switching which is currently active. This way the bus driver would always have data available on the active buffer while uP is writing to the other buffer at a slower rate and doesn't need to try and keep up. 

I really appreciate your help but I don't want to take up more of your time away from your own projects when all I can do is follow along at the moment.

**Comment by kdschlosser** [comment]
I would recommend giving LVGL a try with it. All of that stuff is hidden behind the scenes and is done for you. It uses about 2.5Mb of flash storage if you have just about everything turned on in LVGL. With only the Canvas widget which is what you would use for the purposes of rendering the flash use would be down to 1.8 or 1.9 MB or so.

Python is a much easier language to use if learning. it is harder to go from C to python then it is to go from Python to C,  I can tell you that much. LVGL is very good at what it does and you can set it up to use only the features that you want to save on flash space. There are lots of widgets that are already made that you can use or you  can custom render widgets if that is what you want to do.

See here..
https://www.youtube.com/watch?v=NxQ7cLobr_Q

That is a custom rendered widget written in Python using LVGL. You have to excuse the out of focus look of it, that was caused by the screen recorder I used to make the video. They all want to get paid in order to give better recordings. I have yet to find a good screen recorder that is opensource and runs on Windows.

**Comment by 0ut4t1m3** [comment]
I've been trying to avoid a full blown graphics library but it sounds like it's a much better solution for this board at least. I haven't looked too deeply into the LVGL bindings yet but I'm glad to hear I can work with a slimmed down build if I want to stick with drawing my own screens to start.

I'm not sure if it would suit your needs but Open Broadcast Studio does have an option to save locally.

I'll close this ticket now, thanks again for your help.

**Comment by kdschlosser** [comment]
You can let LVGL handle the dynamics of the frame buffer and getting it transferred to the display and you can render using your own own code and passing the data to the canvas widget in LVGL.
